coverage:
  status:
    project:
      default:
        target: 80%
        threshold: null
        base: 
comment:
    layout: "header, sunburst"

ignore:
- "src/main/java/rubys/ninja/experiments/zah  lenpuzzle/game/Game.java"
