coverage:
  status:
    project:
      default:
        target: 80%
        threshold: null
        base: 
    
    ignore:
    - "src/main/java/rubys/ninja/experiments/zahlenpuzzle/game/SinglePlayerGame.java"

comment:
    layout: "header, sunburst"
